version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/cgpa_calculator
      - JWT_SECRET=your_production_jwt_secret_change_this
      - JWT_EXPIRE=7d
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - cgpa-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=cgpa_calculator
    restart: unless-stopped
    networks:
      - cgpa-network

  # Optional: MongoDB Admin Interface
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - cgpa-network

volumes:
  mongo-data:

networks:
  cgpa-network:
    driver: bridge